services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "10"
      RAM_SIZE: "16G"
      CPU_CORES: "4"
      LANGUAGE: "Turkish"
      KEYBOARD: "tr"
      DISK_SIZE: "256G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 8080:3389/tcp
      - 8080:3389/udp
    volumes:
      - ./windows:/storage
    restart: always
    stop_grace_period: 2m
